version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # ✅ Use Node.js 20 (latest supported)
    commands:
      - echo "Upgrading AWS CDK CLI to the latest version..."
      - npm install -g aws-cdk@latest  # 🔥 Force upgrade CDK CLI
      - echo "Installing project dependencies..."
      - npm install  # Install dependencies

  build:
    commands:
      - echo "Synthesizing CDK application..."
      - npx cdk synth  # Run CDK synth with updated CLI

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
