apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: otel
data:
  config.yaml: |
    extensions:
      sigv4auth:
        service: aps
        region: eu-west-2

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

      hostmetrics:
        scrapers:
          cpu: {}
          disk: {}
          memory: {}
          filesystem: {}
          load: {}
          network: {}

      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['127.0.0.1:9464']

            - job_name: 'kubernetes-control-plane'
              scrape_interval: 10s
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_name]
                  regex: 'kube-apiserver|kube-scheduler|kube-controller-manager'
                  action: keep

            - job_name: 'kubernetes-pods'
              scrape_interval: 10s
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                  replacement: $1
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: (.+)
                  replacement: $1
                - source_labels: [__meta_kubernetes_pod_ip]
                  action: replace
                  target_label: instance
                  regex: (.+)
                  replacement: $1

      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        extra_metadata_labels:
          - container.id

      k8s_cluster:
        collection_interval: 30s
        auth_type: serviceAccount
        node_conditions_to_report: [Ready, MemoryPressure, DiskPressure, NetworkUnavailable]
        allocatable_types_to_report: [cpu, memory, storage, ephemeral-storage]

      k8s_events:
        auth_type: serviceAccount

    processors:
      batch: {}

      resourcedetection/system:
        detectors: [env, system, eks]
        timeout: 2s
        override: false

      resource:
        attributes:
          - action: insert
            key: env.name
            value: ${env:ENV_NAME}
          - action: insert
            key: cluster
            value: ${env:CLUSTER_NAME}

      k8sattributes:
        auth_type: serviceAccount
        passthrough: true
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.container.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

    exporters:
      # Logs
      awscloudwatchlogs:
        region: eu-west-2
        log_group_name: /aws/otel/logs
        log_stream_name: otel-logs

      # Metrics
      awsemf:
        region: eu-west-2
        namespace: OtelMetrics
        dimension_rollup_option: NoDimensionRollup
        resource_to_telemetry_conversion:
          enabled: true
        metric_declarations:
          - dimensions: [["k8s.namespace.name", "k8s.pod.name"]]
            metric_name_selectors:
              - "^k8s.container.*"
          - dimensions: [["k8s.node.name"]]
            metric_name_selectors:
              - "^k8s.node.*"
          - dimensions: [["k8s.namespace.name"]]
            metric_name_selectors:
              - "^k8s.namespace.*"
          - dimensions: [["ClusterName"]]
            metric_name_selectors:
              - "^cluster.*"

      awsxray:
        region: eu-west-2

    service:
      extensions: [sigv4auth]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [awsxray]

        metrics:
          receivers: [hostmetrics, kubeletstats, k8s_cluster, prometheus]
          processors: [batch, resourcedetection/system, resource, k8sattributes]
          exporters: [awsemf]

        logs/pod:
          receivers: [otlp]
          processors: [batch, resource, k8sattributes]
          exporters: [awscloudwatchlogs]

        logs/cluster:
          receivers: [otlp]
          processors: [batch, resource, k8sattributes]
          exporters: [awscloudwatchlogs]
